### ISSUE TITLE
Landsat permission error cascaded to corrupt memory

### ISSUE THREAD

**Issue by jpswinski** [SlideRuleEarth/sliderule#314]
During a selftest run with config-asan, the landsat_reader.lua selftest spun on errors not being able to open the landsat raster files.  This caused a memory error.  See below:

```
2023-09-15T16:23:40.770Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021004T230941.v2.0/HLS.S30.T01UCS.2021004T230941.
2023-09-15T16:23:40.776Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021011T225921.v2.0/HLS.S30.T01UCS.2021011T225921.
2023-09-15T16:23:40.781Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021004T230941.v2.0/HLS.S30.T01UCS.2021004T230941.
2023-09-15T16:23:40.787Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021024T230841.v2.0/HLS.S30.T01UCS.2021024T230841.
2023-09-15T16:23:40.792Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021024T230841.v2.0/HLS.S30.T01UCS.2021024T230841.
2023-09-15T16:23:40.797Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021009T230929.v2.0/HLS.S30.T01UCS.2021009T230929.
2023-09-15T16:23:40.801Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021004T230941.v2.0/HLS.S30.T01UCS.2021004T230941.
2023-09-15T16:23:40.806Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021009T230929.v2.0/HLS.S30.T01UCS.2021009T230929.
2023-09-15T16:23:40.812Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021009T230929.v2.0/HLS.S30.T01UCS.2021009T230929.
2023-09-15T16:23:40.816Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021011T225921.v2.0/HLS.S30.T01UCS.2021011T225921.
2023-09-15T16:23:40.821Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021026T225819.v2.0/HLS.S30.T01UCS.2021026T225819.
2023-09-15T16:23:40.827Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021026T225819.v2.0/HLS.S30.T01UCS.2021026T225819.
2023-09-15T16:23:40.832Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021006T225929.v2.0/HLS.S30.T01UCS.2021006T225929.
2023-09-15T16:23:40.837Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021009T230929.v2.0/HLS.S30.T01UCS.2021009T230929.
2023-09-15T16:23:40.841Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021011T225921.v2.0/HLS.S30.T01UCS.2021011T225921.
2023-09-15T16:23:40.846Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021024T230841.v2.0/HLS.S30.T01UCS.2021024T230841.
2023-09-15T16:23:40.850Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021009T230929.v2.0/HLS.S30.T01UCS.2021009T230929.
2023-09-15T16:23:40.856Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021026T225819.v2.0/HLS.S30.T01UCS.2021026T225819.
2023-09-15T16:23:40.861Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021011T225921.v2.0/HLS.S30.T01UCS.2021011T225921.
2023-09-15T16:23:40.866Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021004T230941.v2.0/HLS.S30.T01UCS.2021004T230941.
2023-09-15T16:23:40.871Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021026T225819.v2.0/HLS.S30.T01UCS.2021026T225819.
2023-09-15T16:23:40.876Z 172.31.29.82:CRITICAL:GdalRaster.cpp:181 Error sampling: Failed to opened raster: /vsis3/lp-prod-protected/HLSS30.020/HLS.S30.T01UCS.2021016T225909.v2.0/HLS.S30.T01UCS.2021016T225909.
POI sample time: 8.58   (27 threads)

-------------------------------------------------
Landsat AOI Subset test
-------------------------------------------------
AddressSanitizer:DEADLYSIGNAL
=================================================================
==266628==ERROR: AddressSanitizer: SEGV on unknown address 0xffffab1cd900 (pc 0xffffb21440a0 bp 0xffff635fc2a0 sp 0xffff635fc2a0 T131)
==266628==The signal is caused by a WRITE memory access.
    #0 0xffffb21440a0 in CPLAtomicAdd /home/jswinski/dependencies/gdal/port/cpl_atomic_ops.cpp:105:48
    #1 0xffffb24b8eac in OGRSpatialReference::Dereference() /home/jswinski/dependencies/gdal/ogr/ogrspatialreference.cpp:1030:12
    #2 0xffffb24b8f50 in OGRSpatialReference::Release() /home/jswinski/dependencies/gdal/ogr/ogrspatialreference.cpp:1077:20
    #3 0xffffb2472b6c in OGRGeometry::~OGRGeometry() /home/jswinski/dependencies/gdal/ogr/ogrgeometry.cpp:134:58
    #4 0xffffb245a9e4 in OGRPoint::~OGRPoint() /home/jswinski/dependencies/gdal/ogr/ogr_geometry.h:1083:15
    #5 0xffffb245aa04 in OGRPoint::~OGRPoint() /home/jswinski/dependencies/gdal/ogr/ogr_geometry.h:1083:15
    #6 0xffffb24457a8 in OGR_G_DestroyGeometry /home/jswinski/dependencies/gdal/ogr/ogrgeometryfactory.cpp:703:41
    #7 0x6f0ed0 in GeoIndexedRaster::sampleRasters(OGRGeometry*) /home/jswinski/meta/sliderule/packages/geo/GeoIndexedRaster.cpp:414:29
    #8 0x6ecc68 in GeoIndexedRaster::sample(OGRGeometry*, long) /home/jswinski/meta/sliderule/packages/geo/GeoIndexedRaster.cpp:472:9
    #9 0x6ed328 in GeoIndexedRaster::getSubsets(double, double, double, double, long, std::vector<RasterSubset*, std::allocator<RasterSubset*> >&, void*) /home/jswinski/meta/sliderule/packages/geo/GeoIndexedRaster.cpp:149:9
    #10 0x70d364 in RasterObject::luaSubset(lua_State*) /home/jswinski/meta/sliderule/packages/geo/RasterObject.cpp:297:18
    #11 0xffffb534e93c  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xc93c)
    #12 0xffffb535be24  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x19e24)
    #13 0xffffb534ed50  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd50)
    #14 0xffffb534ed94  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd94)
    #15 0xffffb534a368 in lua_callk (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x8368)
    #16 0xffffb5360acc  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x1eacc)
    #17 0xffffb534e93c  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xc93c)
    #18 0xffffb535be24  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x19e24)
    #19 0xffffb534ed50  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd50)
    #20 0xffffb534ed94  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd94)
    #21 0xffffb534e128  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xc128)
    #22 0xffffb534f024  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xd024)
    #23 0xffffb534a438 in lua_pcallk (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x8438)
    #24 0x5b1b28 in LuaEngine::docall(int, int) /home/jswinski/meta/sliderule/packages/core/LuaEngine.cpp:813:14
    #25 0x5b3110 in LuaEngine::handlescript(char const*) /home/jswinski/meta/sliderule/packages/core/LuaEngine.cpp:1009:18
    #26 0x5b1400 in LuaEngine::pmain(lua_State*) /home/jswinski/meta/sliderule/packages/core/LuaEngine.cpp:1125:33
    #27 0xffffb534e93c  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xc93c)
    #28 0xffffb534ed14  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd14)
    #29 0xffffb534ed94  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xcd94)
    #30 0xffffb534e128  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xc128)
    #31 0xffffb534f024  (/lib/aarch64-linux-gnu/liblua5.3.so.0+0xd024)
    #32 0xffffb534a438 in lua_pcallk (/lib/aarch64-linux-gnu/liblua5.3.so.0+0x8438)
    #33 0x5adbc8 in LuaEngine::protectedThread(void*) /home/jswinski/meta/sliderule/packages/core/LuaEngine.cpp:548:22
    #34 0xffffb5454620 in start_thread /build/glibc-RIFKjK/glibc-2.31/nptl/pthread_create.c:477:8
    #35 0xffffb1589498  /build/glibc-RIFKjK/glibc-2.31/misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:78

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jswinski/dependencies/gdal/port/cpl_atomic_ops.cpp:105:48 in CPLAtomicAdd
Thread T131 created by T0 here:
    #0 0x4f6bc4 in pthread_create (/home/jswinski/meta/sliderule/stage/sliderule/bin/sliderule-v3.7.0+0x4f6bc4)
    #1 0x77b838 in Thread::Thread(void* (*)(void*), void*, bool) /home/jswinski/meta/sliderule/platforms/linux/Thread.cpp:69:15
    #2 0x5ad1b4 in LuaEngine::LuaEngine(char const*, int, char (*) [1024], unsigned int, void (*)(lua_State*, lua_Debug*), bool) /home/jswinski/meta/sliderule/packages/core/LuaEngine.cpp:93:28
    #3 0x53cb9c in main /home/jswinski/meta/sliderule/targets/server-linux/SlideRule.cpp:336:34
    #4 0xffffb14d8e0c in __libc_start_main /build/glibc-RIFKjK/glibc-2.31/csu/../csu/libc-start.c:308:16
    #5 0x49cc38 in _start (/home/jswinski/meta/sliderule/stage/sliderule/bin/sliderule-v3.7.0+0x49cc38)

==266628==ABORTING
make: *** [Makefile:148: selftest] Error 1
```

**Comment by elidwa** [comment]
Closing this issue. Since the introduction of batch sampling mode, the relevant code has significantly changed. I instrumented the code to force raster open failures and attempted to reproduce the original error (AddressSanitizer: SEGV), but was unable to do so. 
There have been no recent reports of similar (or any other) segfaults.
