### ISSUE TITLE
Selftest fails with ClusterSocket memory leak

### ISSUE THREAD

**Issue by jpswinski** [SlideRuleEarth/sliderule#396]
```
*********************************
Total number of asserts: 575
Total number of errors: 0
*********************************

Exiting... cleanup complete (0 errors)

=================================================================
==1619==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 65568 byte(s) in 1 object(s) allocated from:
    #0 0x63dc01 in operator new(unsigned long) (/__w/sliderule/sliderule/stage/sliderule/bin/sliderule-v4.4.0+0x63dc01) (BuildId: 6d396c4510be64ad60f5285b48df3ac138a9aac3)
    #1 0x65d80c in ClusterSocket::onConnect(int) /__w/sliderule/sliderule/packages/core/ClusterSocket.cpp:591:41
    #2 0x65995d in ClusterSocket::activeHandler(int, int, void*) /__w/sliderule/sliderule/packages/core/ClusterSocket.cpp:294:44
    #3 0x92b006 in SockLib::startclient(char const*, int, int, int (*)(int, short*, void*), int (*)(int, int, void*), bool const*, void*, bool*) /__w/sliderule/sliderule/platforms/linux/SockLib.cpp:681:20
    #4 0x658afd in ClusterSocket::connectionThread(void*) /__w/sliderule/sliderule/packages/core/ClusterSocket.cpp:237:31
    #5 0x7fbb05ca57f1 in start_thread (/lib64/libc.so.6+0x9f7f1) (BuildId: 30448f50[833](https://github.com/SlideRuleEarth/sliderule/actions/runs/8968903999/job/24629259504#step:5:834)6fb6b11d92bcff7f65c300f3e68e1)

SUMMARY: AddressSanitizer: 65568 byte(s) leaked in 1 allocation(s).
make: *** [Makefile:417: selftest] Error 1
Error: Process completed with exit code 2.
```

**Comment by jpswinski** [comment]
Fixed by #402
